### ISSUE TITLE
Cann't start new game.

### ISSUE THREAD

**Issue by o01eg** [gecube/opencaesar3#190]
When I press "Start new career" I get next error:

```
caesar3: /mnt/another/tmp/opencaesar3-gecube/oc3_scopedptr.hpp:73: T* ScopedPtr<T, Cleanup>::operator->() const [with T = io::FilePath::Impl, Cleanup = ScopedPtrDeleter<io::FilePath::Impl>]: Assertion `!(!d)' failed.
```

In debugger:

```
(gdb) bt full
#0  0x00007ffff5fbdaa5 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff5fbeda5 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff5fb6afe in __assert_fail_base () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff5fb6bc0 in __assert_fail () from /lib64/libc.so.6
No symbol table info available.
#4  0x0000000000684fd9 in ScopedPtr<io::FilePath::Impl, ScopedPtrDeleter<io::FilePath::Impl> >::operator-> (this=0x262ed68)
    at /mnt/another/tmp/opencaesar3-gecube/oc3_scopedptr.hpp:73
        __PRETTY_FUNCTION__ = "T* ScopedPtr<T, Cleanup>::operator->() const [with T = io::FilePath::Impl, Cleanup = ScopedPtrDeleter<io::FilePath::Impl>]"
#5  0x000000000068319a in io::FilePath::FilePath (this=0x262b8f0, nPath=...) at /mnt/another/tmp/opencaesar3-gecube/oc3_filepath.cpp:263
No locals.
#6  0x000000000061d012 in io::FileListItem::FileListItem (this=0x262b8f0) at /mnt/another/tmp/opencaesar3-gecube/oc3_filelist_item.hpp:10
No locals.
#7  0x00000000006fdcc1 in __gnu_cxx::new_allocator<io::FileListItem>::construct (this=0x7fffffffd640, __p=0x262b8f0, __val=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.4/include/g++-v4/ext/new_allocator.h:108
No locals.
#8  0x00000000006fde57 in std::vector<io::FileListItem, std::allocator<io::FileListItem> >::_M_insert_aux (this=0x7fffffffd640, 
    __position=<error reading variable: Cannot access memory at address 0x0>, __x=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.4/include/g++-v4/bits/vector.tcc:335
        __len = 1
        __elems_before = 0
        __new_start = 0x262b8f0
        __new_finish = 0x262b8f0
#9  0x00000000006fdbe2 in std::vector<io::FileListItem, std::allocator<io::FileListItem> >::push_back (this=0x7fffffffd640, __x=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.4/include/g++-v4/bits/stl_vector.h:834
No locals.
#10 0x00000000006fcccc in Application::Impl::scanForMaps (this=0xa34280, resourcePath=...) at /mnt/another/tmp/opencaesar3-gecube/oc3_application.cpp:138
        it = {name = {_vptr.FilePath = <vtable for io::FilePath+16>, static anyFile = "*.*", static firstEntry = ".", static secondEntry = "..", _d = {
              d = }}, fullName = {_vptr.FilePath = <vtable for io::FilePath+16>, static anyFile = "*.*", static firstEntry = ".", 
            static secondEntry = "..", _d = {d = }}, size = 211692, iD = 1, Offset = 0, isDirectory = false}
        mapsDir = {<io::FilePath> = {_vptr.FilePath = 0x7508d0 <vtable for io::FileDir+16>, static anyFile = 0x75f760 "*.*", 
            static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x25c51e0}}, <No data fields>}
        items = std::vector of length 13, capacity 16 = {{name = {_vptr.FilePath = 0x262fc40, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x7ffff632c978 <main_arena+856>}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 0, iD = 0, Offset = 0, isDirectory = true}, {name = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, 
              static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, 
            iD = 1, Offset = 0, isDirectory = false}, {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 2, Offset = 0, isDirectory = false}, {name = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, 
              static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, 
            iD = 3, Offset = 0, isDirectory = false}, {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 4, Offset = 0, isDirectory = false}, {name = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, 
              static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, 
            iD = 5, Offset = 0, isDirectory = false}, {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 6, Offset = 0, isDirectory = false}, {name = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, 
              static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, 
            iD = 7, Offset = 0, isDirectory = false}, {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 8, Offset = 0, isDirectory = false}, {name = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, 
              static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, 
            iD = 9, Offset = 0, isDirectory = false}, {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 10, Offset = 0, isDirectory = false}, {name = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, 
              static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, 
            iD = 11, Offset = 0, isDirectory = false}, {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
              static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
              _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
              static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 12, Offset = 0, isDirectory = false}}
        ret = std::vector of length 0, capacity 0
#11 0x00000000006fce96 in Application::setScreenMenu (this=0x7fffffffd810) at /mnt/another/tmp/opencaesar3-gecube/oc3_application.cpp:159
        maps = std::vector of length 0, capacity 0
        file = 
    "\001\000\000\000\000\000\000\000\033\335\377\377\377\177\000\000\000\000\000\000\000\000\000\000G\335\377\377\377\177\000\000S\335\377\377\377\177\000\000i\336\377\377\377\177\000\000|\336\377\377\377\177\000\000\251\336\377\377\377\177\000\000\333\336\377\377\377\177\000\000\353\336\377\377\377\177\000\000\001\337\377\377\377\177\000\000\025\337\377\377\377\177\000\000 \337\377\377\377\177\000\000K\337\377\377\377\177\000\000\232\337\377\377\377\177\000\000\270\337\377\377\377\177\000\000\312\337\377\377\377\177\000\000\364\337\377\377\377\177\000\000\f\340\377\377\377\177\000\000\027\340\377\377\377\177\000\000\204\340\377\377\377\177\000\000\031\346\377\377\377\177\000\000F\346\377\377\377\177\000\000d\346\377\377\377\177\000\000\222\346\377\377\377\177\000\000\342\346\377\377\377\177\000\000\221\347\377\377\377\177\000\000\235\347\377\377\377\177\000\000\272\347\377\377\377\177\000\000\247\350\377\377\377\177\000\000\273\350\377\377\377\177\000\000\335\350\377\377\377\177\000\000\275\351\377\377\377\177\000\000\322\351\377\377\377\177\000\000\347\351\377\377\377\177\000\000\366\351\377\377\377\177\000\000\005\352\377\377\377\177\000\000\026\352\377\377\377\177\000\000>\352\377\377\377\177\000\000z\352\377\377\377\177\000\000\207\352\377\377\377\177\000\000\233\352\377\377\377\177\000\000\335\352\377\377\377\177\000\000\350\352\377\377\377\177\000\000\017\353\377\377\377\177\000\000&\353\377\377\377\177\000\000\067\353\377\377\377\177\000\000O\353\377\377\377\177\000\000h\353\377\377\377\177\000\000q\353\377\377\377\177\000\000\254\353\377\377\377\177\000\000\275\353\377\377\377\177\000\000\305\353\377\377\377\177\000\000\342\353\377\377\377\177\000\000\001\354\377\377\377\177\000\000\256"...<Address 0x7ffffffff000 out of bounds>
        loadok = false
        screen = {<Screen> = {_vptr.Screen = 0x74e890 <vtable for ScreenMenu+16>, _isStopped = false}, Result = ScreenMenu::startNewGame, _d = {
            d = 0x25ab850}}
        result = 0
        scenario = @0xa309f8: {_d = {d = 0x25d0e70}}
        __PRETTY_FUNCTION__ = "void Application::setScreenMenu()"
#12 0x00000000006fd637 in Application::start (this=0x7fffffffd810) at /mnt/another/tmp/opencaesar3-gecube/oc3_application.cpp:248
        __PRETTY_FUNCTION__ = "void Application::start()"
#13 0x00000000006fd914 in main (argc=1, argv=0x7fffffffd968) at /mnt/another/tmp/opencaesar3-gecube/oc3_application.cpp:275
        app = {_d = {d = 0xa34280}}
(gdb) f 5
#5  0x000000000068319a in io::FilePath::FilePath (this=0x262b8f0, nPath=...) at /mnt/another/tmp/opencaesar3-gecube/oc3_filepath.cpp:263
263   _d->path = nPath._d->path;
(gdb) p _d
$4 = {d = 0x2629d60}
(gdb) p nPath._d
$5 = {d = 0x0}
(gdb) f 10
#10 0x00000000006fcccc in Application::Impl::scanForMaps (this=0xa34280, resourcePath=...) at /mnt/another/tmp/opencaesar3-gecube/oc3_application.cpp:138
138       ret.push_back(*it);
(gdb) p *it
$6 = (const io::FileListItem &) @0x262ed60: {name = {_vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", 
    static firstEntry = 0x75f764 ".", static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, fullName = {
    _vptr.FilePath = 0x75fa10 <vtable for io::FilePath+16>, static anyFile = 0x75f760 "*.*", static firstEntry = 0x75f764 ".", 
    static secondEntry = 0x75f766 "..", _d = {d = 0x0}}, size = 211692, iD = 1, Offset = 0, isDirectory = false}
```

Rev: cc6fc0f5aabd143e1c75ff3412d816fd6f29f7c1
Gentoo Linux AMD64
gcc-4.6.4

**Comment by AMDmi3** [comment]
Both the problem and the fix confirmed on FreeBSD.
